---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: nginx-demo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./deploy/nginx-demo
  prune: true
  sourceRef:
    kind: GitRepository
    name: nginx-demo
  validation: client
