---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  validation: client  
  patchesStrategicMerge:
    - apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRoute
      metadata:
        name: podinfo
      spec:
        entryPoints:
          - web
        routes:
          - kind: Rule
            match: PathPrefix(`/`)
            services:
              - name: podinfo
                port: 9898
        tls:
          certResolver: default
          options: {}
